### ISSUE TITLE
NUS-WIDE

### ISSUE THREAD

**Issue by dawang-11** [jasonseu/SALGL#2]
你好、我在下载这个数据集的时候没有Flickr这个文件欸

**Comment by jasonseu** [comment]
> 你好、我在下载这个数据集的时候没有Flickr这个文件欸

感谢关注，Flickr文件夹包含了所有图片，是需要跟数据集的作者发邮件申请的。具体细节可以参见[NUS-WIDE官网](https://lms.comp.nus.edu.sg/wp-content/uploads/2019/research/nuswide/NUS-WIDE.html)。

**Comment by dawang-11** [comment]
好滴谢谢你，我试了好几个邮箱联系数据集的作者，不知道啥原因，都是退回




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jasonseu/SALGL"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月7日(星期二) 中午11:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jasonseu/SALGL] NUS-WIDE (Issue #2)





  
你好、我在下载这个数据集的时候没有Flickr这个文件欸
  
感谢关注，Flickr文件夹包含了所有图片，是需要跟数据集的作者发邮件申请的。具体细节可以参见NUS-WIDE官网。
